# config/config.yml
development:
  theme: "wow"
  att_style:
:original: 
- 1920x1680>
- :jpg
:small: 
- 100x100#
- :jpg
:medium: 
- 250x250
- :jpg
:large: 
- 500x500>
- :jpg

test:
  theme: "wow"
  att_style:
:original: 
- 1920x1680>
- :jpg
:small: 
- 100x100#
- :jpg
:medium: 
- 250x250
- :jpg
:large: 
- 500x500>
- :jpg

production:
  theme: "wow"
  att_style:
:original: 
- 1920x1680>
- :jpg
:small: 
- 100x100#
- :jpg
:medium: 
- 250x250
- :jpg
:large: 
- 500x500>
- :jpg
