# config/config.yml
defaults: &defaults
  application_title: "MariCMS"
  current_theme: "default"
  image_style: 
    key: "default"
    name: "Default"
    width: 1920
    height: 1080
    format: "jpg" 
    quality: 90
    crop: false
    # child_image_styles:
    # - key: "small"
    #   name: "Small"
    #   width: 80
    #   height: 80
    #   format: "jpg" 
    #   quality: 90
    #   crop: true
  date_format: "%Y-%m-%d"
  time_format: "%H:%M"
  attachment_max_size: ""
  host_name: "localhost"
  ruby_home: "/usr/local/ruby/"
  repo_root: "/home/www/"
	
development:
  <<: *defaults
	
test:
  <<: *defaults
  
production:
  <<: *defaults