# config/config.yml
defaults: &defaults
  application_title: "TianTing"
  current_theme: "default"
  image_style: 
    :original: 
      :geometry: 1920x1680>
      :format: jpg
    :large: 
      :geometry: 500x500>
      :format: jpg
    :medium: 
      :geometry: 250x250#
      :format: jpg
    :small: 
      :geometry: 80x80#
      :format: jpg
  date_format: "%Y-%m-%d"
  time_format: "%H:%M"
  attachment_max_size: ""
  per_page: 5
  host_name: "localhost"
	
development:
  <<: *defaults
	
test:
  <<: *defaults
  
production:
  <<: *defaults