development:
    adapter: mongodb
    server: localhost
    database: tian-ting-dev
    port: 27017
    
test:
    adapter: mongodb
    server: localhost
    database: tian-ting-test
    port: 27017
    
production:
    adapter: mongodb
    server: localhost
    database: tian-ting
    port: 27017